[project]
name = "quantization-spurious-heuristics-in-transformers"
version = "0.1.0"
description = "Investigating quantization and spurious linguistic heuristics in Transformers"
readme = "README.md"
requires-python = ">=3.12,<3.13"

dependencies = [
    "torch",
    "transformers",
    "datasets",
    "accelerate",
    "evaluate",
    "scikit-learn",
    "scipy",
    "pandas",
    "numpy",
    "matplotlib",
    "jupyter>=1.1.1",
    "ipykernel>=7.3.0",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu130", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
